### ISSUE TITLE
WorkflowInstance class needs to be renamed to Workflow.

### ISSUE THREAD

**Issue by cburn17** [CSS553-Team4/provenance#4]
Runner::executeWorkflow was specified to take a Workflow as an input parameter, but since Workflow was written as an interface, it is not possible to create an instance of it.
WorkflowInstance is a class, not an instance of a class, so it is misnamed anyway.
Please rename Workflow to WorkflowInterface, and WorkflowInstance to Workflow.

**Comment by the-brickster** [comment]
Workflow was workflowinterface before, I don't why it was changed
